# Estações BRT Belém

''' Stations groups:
    - 0: Estação muito movimentada
    - 1: Estação movimentada
    - 2: Estação pouco movimentada

    Station sides:
    - A: Parada do lado de ida
    - B: Parada do lado de volta
    - None: Parada em ambos os sentidos
'''
stations = [
    {'name': 'Terminal Maracacuera',
    'location': 0,
    'side': None,
    'group': 0
    },
    {'name': 'Estação Castro Moura',
    'location': 1.4,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Eduardo Angelim',
    'location': 2.0,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Grêmio Literário',
    'location': 2.6,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Maguari',
    'location': 3.9,
    'side': None,
    'group': 2
    },
    {'name': 'Estação José Homobono',
    'location': 4.8,
    'side': None,
    'group': 2
    },
    {'name': 'Terminal Tapanã',
    'location': 5.8,
    'side': None,
    'group': 0
    },
    {'name': 'Estação Sideral',
    'location': 6.5,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Morada do Sol',
    'location': 7.6,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Parque Shopping',
    'location': 8.3,
    'side': None,
    'group': 1
    },
    {'name': 'Terminal Mangueirão',
    'location': 10.0,
    'side': None,
    'group': 1
    },
    {'name': 'Estação Templo do Centenário',
    'location': 10.7,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Marinha',
    'location': 11.8,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Marambaia',
    'location': 12.3,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Tavares Bastos',
    'location': 14.0,
    'side': None,
    'group': 2
    },
    {'name': 'Estação Tuna Luso',
    'location': 14.8,
    'side': 'B',
    'group': 2
    },
    {'name': 'Estação Império Amazônico',
    'location': 14.9,
    'side': 'A',
    'group': 2
    },
    {'name': 'Estação Júlio César (Aeronáutica)',
    'location': 15.5,
    'side': 'B',
    'group': 2
    },
    {'name': 'Estação Júlio César',
    'location': 15.7,
    'side': 'A',
    'group': 1
    },
    {'name': 'Estação Bosque (Ida)',
    'location': 16.5,
    'side': 'A',
    'group': 1
    },
    {'name': 'Estação Bosque (Volta)',
    'location': 16.9,
    'side': 'B',
    'group': 2
    },
    {'name': 'Estação Mauriti (Volta)',
    'location': 17.4,
    'side': 'B',
    'group': 1
    },
    {'name': 'Estação Mauriti (Ida)',
    'location': 17.5,
    'side': 'A',
    'group': 1
    },
    {'name': 'Estação Humaitá (Volta)',
    'location': 17.9,
    'side': 'B',
    'group': 1
    },
    {'name': 'Estação Humaitá (Ida)',
    'location': 18.1,
    'side': 'A',
    'group': 1
    },
    {'name': 'Estação Antônio Baena (Volta)',
    'location': 18.5,
    'side': 'B',
    'group': 1
    },
    {'name': 'Estação Antônio Baena (Ida)',
    'location': 18.6,
    'side': 'A',
    'group': 1
    },
    {'name': 'Terminal São Brás',
    'location': 19.1,
    'side': 'B',
    'group': 0
    },
]

''' Traffic light groups:
    - 0: Cruzamento movimentado
    - 1: Cruzamento comum
    - 2: Travessia de pedestres
'''
traffic_lights = [
    {'perimeter': 'Supermercado Armazém',
    'location': 0.2,
    'group': 2,
    },
    {'perimeter': 'Estação Castro Moura',
    'location': 1.4,
    'group': 2,
    },
    {'perimeter': 'Augusto Montenegro com Rua Alacide Nunes (Tenoné)',
    'location': 3.4,
    'group': 1,
    },
    {'perimeter': 'Estação Maguari',
    'location': 4.0,
    'group': 2,
    },
    {'perimeter': 'Augusto Montenegro com Avenida Principal (Conj Maguari)',
    'location': 4.1,
    'group': 1,
    },
    {'perimeter': 'Retorno Augusto Montenegro (Líder Augusto Montenegro)',
    'location': 5.1,
    'group': 1,
    },
    {'perimeter': 'Augusto Montenegro com Mário Covas (Satélite)',
    'location': 5.8,
    'group': 0,
    },
    {'perimeter': 'Augusto Montenegro com Estrada do Tapanã',
    'location': 6.1,
    'group': 0,
    },
    {'perimeter': 'Augusto Montenegro com Rua Sideral',
    'location': 6.8,
    'group': 1,
    },
    {'perimeter': 'Colégio Pequeno Príncipe Avante',
    'location': 7.3,
    'group': 2,
    },
    {'perimeter': 'Condomínio Sol Nascente',
    'location': 7.7,
    'group': 2,
    },
    {'perimeter': 'Retorno Augusto Montenegro (Colégio Paulista Belém)',
    'location': 8.1,
    'group': 1,
    },
    {'perimeter': 'Estação Parque Shopping',
    'location': 8.5,
    'group': 2,
    },
    {'perimeter': 'Conjunto Natália Lins',
    'location': 9.7,
    'group': 2,
    },
    {'perimeter': 'Terminal Mangueirão',
    'location': 9.9,
    'group': 1,
    },
    {'perimeter': 'Retorno Augusto Montenegro (Mangueirinho)',
    'location': 10.4,
    'group': 1,
    },
    {'perimeter': 'Estação Templo do Centenário',
    'location': 10.8,
    'group': 2,
    },
    {'perimeter': 'Retorno Augusto Montenegro (Marinha)',
    'location': 11.7,
    'group': 1,
    },
    {'perimeter': 'Augusto Montenegro com Rua da Marinha',
    'location': 11.9,
    'group': 1,
    },
    {'perimeter': 'Augusto Montenegro (Marambaia)',
    'location': 12.3,
    'group': 2,
    },
    {'perimeter': 'Colégio Santa Madre',
    'location': 12.6,
    'group': 2,
    },
    {'perimeter': 'Augusto Montenegro com Entroncamento',
    'location': 12.9,
    'group': 2,
    },
    {'perimeter': 'Almirante Barroso com Tavares Bastos',
    'location': 14.0,
    'group': 0,
    },
    {'perimeter': 'Almirante Barroso com Tavares Bastos',
    'location': 14.0,
    'group': 0,
    },
    {'perimeter': 'Estação Tuna Luso',
    'location': 14.8,
    'group': 2,
    },
    {'perimeter': 'Almirante Barroso com Av Júlio César',
    'location': 15.5,
    'group': 0,
    },
    {'perimeter': 'Almirante Barroso com Av Doutor Freitas',
    'location': 16.1,
    'group': 1,
    },
    {'perimeter': 'Almirante Barroso com Tv Perebebuí',
    'location': 16.4,
    'group': 2,
    },
    {'perimeter': 'Almirante Barroso com Tv Lomas Valentinas',
    'location': 16.8,
    'group': 0,
    },
    {'perimeter': 'Av Almirante Barroso com Tv Angustugra',
    'location': 17.0,
    'group': 1,
    },
    {'perimeter': 'Av Almirante Barroso com Tv Mauriti',
    'location': 17.3,
    'group': 0,
    },
    {'perimeter': 'Av Almirante Barroso com Tv da Estrella',
    'location': 17.5,
    'group': 1,
    },
    {'perimeter': 'Escola Visconde de Souza Franco',
    'location': 17.7,
    'group': 2,
    },
    {'perimeter': 'Av Almirante Barroso com Tv Vileta',
    'location': 17.8,
    'group': 1,
    },
    {'perimeter': 'Av Almirante Barroso com Tv Humaitá',
    'location': 18.0,
    'group': 0,
    },
    {'perimeter': 'Av Almirante Barroso com Tv Antônio Baena',
    'location': 18.5,
    'group': 1,
    },
    {'perimeter': 'Av Almirante Barroso com Av Ceará',
    'location': 18.8,
    'group': 0,
    },
]

print(len(traffic_lights))
print(len(stations))